version: '3'

set: [errexit, pipefail]

silent: true

vars:
  # Core paths
  HOME: '{{.HOME}}'
  XDG_CONFIG_HOME: '{{.HOME}}/.config'
  XDG_DATA_HOME: '{{.HOME}}/.local/share'
  XDG_STATE_HOME: '{{.HOME}}/.local/state'
  XDG_CACHE_HOME: '{{.HOME}}/.cache'
  ZDOTDIR: '{{.XDG_CONFIG_HOME}}/zsh'
  
  # Dotfiles paths
  DOTFILEDIR:
    sh: cd "$(dirname "$(realpath "${BASH_SOURCE[0]:-$0}")")" 2>/dev/null && pwd || pwd
  
  # Profile configuration
  VALID_PROFILES: "personal server work test"
  PROFILE_FILE: '{{.XDG_CONFIG_HOME}}/dotfiles/profile'
  PROFILE: 
    sh: |
      if [[ -f "{{.PROFILE_FILE}}" ]]; then
        cat "{{.PROFILE_FILE}}" 2>/dev/null | tr -d '[:space:]'
      fi
  
  # Homebrew prefix - defined here so all taskfiles can access it
  HOMEBREW_PREFIX:
    sh: |
      # Use existing brew if available, otherwise detect by architecture
      if command -v brew &>/dev/null; then
        brew --prefix
      elif [[ "$(uname)" == "Darwin" ]]; then
        [[ "$(uname -m)" == "arm64" ]] && echo "/opt/homebrew" || echo "/usr/local"
      else
        echo "/home/linuxbrew/.linuxbrew"
      fi
  
  # Homebrew shellenv setup - ensures brew is available in each shell context
  BREW_SHELLENV: |
    if [[ -x "{{.HOMEBREW_PREFIX}}/bin/brew" ]]; then
      eval "$({{.HOMEBREW_PREFIX}}/bin/brew shellenv)"
    fi

  # Consistent messages sourcing for all taskfiles
  DOTFILES_MESSAGES: |
    source '{{.DOTFILEDIR}}/install/messages.zsh'

includes:
  common: ./taskfiles/common.yml
  profile: ./taskfiles/profile.yml
  links: ./taskfiles/links.yml
  brew: ./taskfiles/brew.yml
  macos: ./taskfiles/macos.yml
  personal:
    taskfile: ./taskfiles/profile-tasks.yml
    vars:
      TARGET_PROFILE: personal
  work:
    taskfile: ./taskfiles/profile-tasks.yml
    vars:
      TARGET_PROFILE: work
  server:
    taskfile: ./taskfiles/profile-tasks.yml
    vars:
      TARGET_PROFILE: server

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - |
        # Filter out profile-specific tasks from the list
        PROFILES_PATTERN=$(echo "{{.VALID_PROFILES}}" | tr ' ' '|')
        
        # Use sed to strip ANSI codes, then filter, preserving the original colored output via process substitution
        task --list --color | while IFS= read -r line; do
          # Strip ANSI codes for pattern matching
          stripped=$(echo "$line" | sed 's/\x1b\[[0-9;]*m//g')
          # Check if it matches a profile task pattern
          if ! echo "$stripped" | grep -qE "^\* ($PROFILES_PATTERN):"; then
            echo "$line"
          fi
        done

  install:
    desc: "Full dotfiles installation"
    summary: |
      Installs all dotfiles components for the configured profile.
      
      Usage:
        ./bootstrap.zsh              # Fresh install (prompts for profile)
        task install                 # Re-install with saved profile (also prompts for profile if missing)
    cmds:
      - |
        {{.DOTFILES_MESSAGES}}
        info "Starting installation..."
      - task: common:xdg
      - task: profile:ensure
      - task: common:zdotdir
      - task: links:all
      - task: brew:install
      - task: macos:defaults
      - task: macos:shell
      - task: profile:install
      - |
        {{.DOTFILES_MESSAGES}}
        success "Installation complete for profile {{.PROFILE}}"
        success "If this is a brand new install, please restart your system to ensure all settings take effect."

  update:
    desc: "Update dotfiles and all dependencies"
    summary: |
      Updates the dotfiles installation:
        - Pulls latest from git
        - Updates Homebrew packages
        - Updates oh-my-zsh
        - Updates tldr definitions
        - Updates antigen plugins
        - Re-runs profile installation
    cmds:
      - |
        {{.DOTFILES_MESSAGES}}
        info "Updating dotfiles..."
      - cmd: 'git pull'
      - cmd: 'zsh "$ZSH/tools/upgrade.sh"'
      - cmd: 'tldr --update'
      - task: common:antigen-update
      - task: install

  validate:
    desc: "Validate dotfiles installation"
    cmds:
      - |
        {{.DOTFILES_MESSAGES}}
        info "Validating installation for profile: {{.PROFILE}}"
      
      # Validate each component via its own taskfile
      - task: common:validate
      - task: profile:validate
      - task: links:validate
      - task: brew:validate
      - task: macos:validate
      
      # Profile-specific validation (conditional)
      - |
        {{.DOTFILES_MESSAGES}}
        task "{{.PROFILE}}:validate"
        success "Validation complete"

  clean:
    desc: "Remove caches and generated files"
    cmds:
      - rm -rf {{.XDG_CACHE_HOME}}/antigen
      - rm -rf {{.XDG_CACHE_HOME}}/zsh
      - |
        {{.DOTFILES_MESSAGES}}
        success "Caches cleaned"
