###############################
#  Taps                       #
###############################

tap "homebrew/homebrew-cask"
tap "homebrew/cask-versions"

###############################
#  Binaries                   #
###############################

brew "wget"
brew "glow" # https://github.com/charmbracelet/glow
brew "highlight"
brew "pcre" 
brew "htop"

