#!/bin/zsh
# Post-tool hook: warn if AI attribution comments were written.
# Non-blocking (exit 0) -- just prints a warning for Claude to fix.

set -euo pipefail
source "${0:A:h}/lib.zsh"

hook::require_ggrep warn
hook::read_stdin

content="$(hook::extract '(.tool_input.content // "") + (.tool_input.new_string // "") + (.tool_input.command // "")')"
[[ -z "$content" ]] && exit 0

# Case-insensitive check for AI attribution patterns
hook::match_patterns "$content" 0 "WARNING: AI attribution detected -- remove it" \
  'generated by (claude|ai|copilot|chatgpt|gpt|anthropic)' \
  'written by (claude|ai|copilot|chatgpt|gpt|anthropic)' \
  'created by (claude|ai|copilot|chatgpt|gpt|anthropic)' \
  'ai-generated' \
  'auto-generated by' \
  'co-authored-by:.*\b(claude|copilot|chatgpt|gpt|anthropic)\b' \
  'generated with \[?claude'

exit 0
