#!/bin/zsh

# =============================================================================
# claude/hooks/no-ai-comments.zsh -- post-tool hook: warn on AI attribution
#
# Purpose:      Non-blocking warning when AI-attribution patterns appear in
#               tool output (exit 0 always; prints warning to stderr).
# Depends on:   claude/hooks/lib.zsh; jq; ggrep.
# Side effects: writes WARNING line to stderr on attribution match.
# =============================================================================

set -euo pipefail
source "${0:A:h}/lib.zsh"

hook::require_ggrep warn
hook::read_stdin

content="$(hook::extract '(.tool_input.content // "") + (.tool_input.new_string // "") + (.tool_input.command // "")')"
[[ -z "$content" ]] && exit 0

# Case-insensitive AI-attribution patterns.
hook::match_patterns "$content" 0 "WARNING: AI attribution detected -- remove it" \
  'generated by (claude|ai|copilot|chatgpt|gpt|anthropic)' \
  'written by (claude|ai|copilot|chatgpt|gpt|anthropic)' \
  'created by (claude|ai|copilot|chatgpt|gpt|anthropic)' \
  'ai-generated' \
  'auto-generated by' \
  'co-authored-by:.*\b(claude|copilot|chatgpt|gpt|anthropic)\b' \
  'generated with \[?claude'

exit 0
