#!/bin/zsh

# =============================================================================
# install/compose-brewfile.zsh -- compose per-machine Brewfile from manifest
#
# Purpose:      Read $XDG_STATE_HOME/dotfiles/resolved.json and emit a
#               composed per-machine Brewfile to $XDG_CACHE_HOME/dotfiles/
#               Brewfile (atomic mktemp + mv).
# Depends on:   jq (>= 1.7), zsh (>= 5); install/messages.zsh.
# Side effects: writes $XDG_CACHE_HOME/dotfiles/Brewfile.
# =============================================================================

set -euo pipefail

# Output structure (composed Brewfile written to $XDG_CACHE_HOME/dotfiles/Brewfile):
#   Line 1    -- AUTO-GENERATED header banner (ISO-8601 UTC timestamp)
#   Lines 2-5 -- Machine: / Bundles: / Extras: counts / DO NOT EDIT notice
#   Body      -- typed extras emitted as Ruby DSL lines, in fixed order:
#                  formulae -> casks -> mas
#
# The resolver folds each shared-bundle's typed buckets (manifests/shared/
# <bundle>.toml `.packages.brew.{formulae,casks,mas}`) into resolved.json's
# packages.brew.extra_packages during resolve, so the composer no longer
# concatenates per-bundle .rb files. `bundles` survives in resolved.json
# for the header-banner trace; it does not gate any composer behavior.
#
# Extras line shapes (canonical; literal single-quotes around the name):
#   brew '<name>'                              (formula -- string OR {name,...} object)
#   cask '<name>'                              (cask)
#   mas  '<name>', id: <id>                    (Mac App Store entry)
#
# packages:verify is brew-info-driven (not bundle-comment-driven). The schema
# still permits {name, verify} formula objects for backward-compat, but the
# `verify` field is ignored on emit -- both string and object shapes produce
# the bare `brew '<name>'` line.

# messages.zsh self-guards under set -u via the `:-` default expansion on
# $DOTFILES_MESSAGES_LOADED; a bare source is sufficient and idempotent.
: "${DOTFILEDIR:?DOTFILEDIR not set -- run via 'task packages:*' or export it manually}"
source "${DOTFILEDIR}/install/messages.zsh"

typeset -r STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/dotfiles"
typeset -r RESOLVED_JSON="${STATE_DIR}/resolved.json"
typeset -r MACHINE_FILE="${STATE_DIR}/machine"
typeset -r CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/dotfiles"
typeset -r COMPOSED_OUT="${CACHE_DIR}/Brewfile"

# Literal single-quote (U+0027) injected as a jq --arg parameter so jq
# filter strings can stay inside zsh single-quote wrapping with no brittle
# nested shell-escape sequences. jq supports JSON \uXXXX escapes only, not
# \xHH, so injecting the byte as data via --arg is the canonical approach.
typeset -r SQ=$'\x27'

# read_machine_name: header-banner helper; never load-bearing for compose
# correctness. Falls back from $MACHINE_FILE to .meta.description to "unknown".
read_machine_name() {
  local name=""
  if [[ -s "$MACHINE_FILE" ]]; then
    read -r name < "$MACHINE_FILE" || true
  fi
  if [[ -z "$name" ]]; then
    name=$(jq -r '.meta.description // "unknown"' "$RESOLVED_JSON" 2>/dev/null || echo "unknown")
  fi
  echo "${name:-unknown}"
}

# compose <out_tmp> <formulae_json> <casks_json> <mas_json>
compose() {
  local out_tmp="$1"
  local formulae_json="$2"
  local casks_json="$3"
  local mas_json="$4"

  local timestamp machine_name
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  machine_name=$(read_machine_name)

  local -a bundles
  bundles=( $(jq -r '.packages.brew.bundles[]' "$RESOLVED_JSON") )

  local bundles_csv=""
  local b
  for b in "${bundles[@]}"; do
    if [[ -z "$bundles_csv" ]]; then
      bundles_csv="$b"
    else
      bundles_csv="${bundles_csv}, $b"
    fi
  done

  local n_formulae n_casks n_mas
  n_formulae=$(echo "$formulae_json" | jq -r 'length')
  n_casks=$(echo "$casks_json"       | jq -r 'length')
  n_mas=$(echo "$mas_json"           | jq -r 'length')

  {
    echo "# AUTO-GENERATED by task packages:compose on ${timestamp}"
    echo "# Machine:  ${machine_name}"
    echo "# Bundles:  ${bundles_csv}"
    echo "# Extras:   ${n_casks} casks, ${n_mas} mas, ${n_formulae} formulae"
    echo "# DO NOT EDIT -- regenerated on every task install."
    echo ""

    # Canonical jq emit forms. Both formula shapes (bare string OR
    # {name, ...} object) emit the same bare `brew '<name>'` line. SQ
    # passed as $q so the jq filter stays inside zsh single-quote wrapping.
    echo "# === formulae ==="
    echo "$formulae_json" | jq -r --arg q "$SQ" '.[] | if type == "string" then "brew " + $q + . + $q else "brew " + $q + .name + $q end'

    echo "# === casks ==="
    echo "$casks_json" | jq -r --arg q "$SQ" '.[] | "cask " + $q + .name + $q'

    echo "# === mas ==="
    echo "$mas_json" | jq -r --arg q "$SQ" '.[] | "mas " + $q + .name + $q + ", id: " + (.id | tostring)'
  } > "$out_tmp"
}

main() {
  if [[ ! -s "$RESOLVED_JSON" ]]; then
    error "resolved.json missing or empty: ${RESOLVED_JSON}"
    error "  run: task setup -- <machine-name>"
    return 1
  fi

  # `// []` covers the case where a sub-array is absent (defense-in-depth
  # for ad-hoc resolved.json variants where defaults didn't supply the shape).
  local formulae_json casks_json mas_json
  formulae_json=$(jq -c '.packages.brew.extra_packages.formulae // []' "$RESOLVED_JSON")
  casks_json=$(jq -c    '.packages.brew.extra_packages.casks    // []' "$RESOLVED_JSON")
  mas_json=$(jq -c      '.packages.brew.extra_packages.mas      // []' "$RESOLVED_JSON")

  # Atomic write: mktemp in the same directory as the destination so `mv`
  # is an atomic rename across the same filesystem (POSIX rename(2)).
  # Signal trap mirrors resolver.zsh: clean up the tmp file on EXIT/INT/TERM,
  # then clear the trap once the rename completes so the (now-renamed)
  # destination is not subsequently rm'd.
  mkdir -p "$CACHE_DIR"
  local tmp
  tmp=$(mktemp "${COMPOSED_OUT}.XXXXXX")
  trap 'rm -f "$tmp"' EXIT INT TERM
  {
    compose "$tmp" "$formulae_json" "$casks_json" "$mas_json"
    mv "$tmp" "$COMPOSED_OUT"
  } || {
    rm -f "$tmp"
    trap - EXIT INT TERM
    return 1
  }
  trap - EXIT INT TERM

  check "composed Brewfile -> ${COMPOSED_OUT}"
  return 0
}

main "$@"
